[default]
description = "Default permissions for the WASAPI audio capture plugin"
permissions = [
    "allow-list-devices",
    "allow-list-processes",
    "allow-start-capture",
    "allow-stop-capture",
]
